services:
  # auth_service:
  #   build: ./auth_service
  #   container_name: auth_service
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - ./auth_service:/app
  game_service:
    build: ./game-service
    container_name: game-service
    ports:
      - 3000:3000
    volumes:
      - ./game-service:/app
  matchmaking_service:
    build: ./matchmaking-service
    container_name: matchmaking-service
    ports:
      - 3001:3000
    volumes:
      - ./matchmaking-service:/app
