services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    depends_on:
      - auth_service_db_init
    ports:
      - 80:3000
    volumes:
      - ./auth_service/dist:/app/dist
      - sqlite_db_data:/sqlite_db_data
    networks:
      - transcendence

  auth_service_db_init:
    build:
      context: ./auth_service_db_init
      dockerfile: Dockerfile
    container_name: auth_service_db_init
    volumes:
      - sqlite_db_data:/sqlite_db_data
    networks:
      - transcendence


networks:
  transcendence:
    driver: bridge


volumes:
  # sqlite
  sqlite_db_data: