services:
  # auth_service:
  #   build: ./auth_service
  #   container_name: auth_service
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - ./auth_service:/app
  game_service:
    build: ./game-service
    container_name: game-service
    ports:
      - 3000:3000
    volumes:
      - ./game-service:/app
  matchmaking_service:
    build: ./matchmaking-service
    container_name: matchmaking-service
    ports:
      - 3001:3000
    volumes:
      - ./matchmaking-service:/app
# RabbitMQ Service
  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management console port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
    #   - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
