services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      - auth_service_db_init
    volumes:
      - sqlite_db_data:/sqlite_db_data
      - static_data:/static_data
    networks:
      - transcendence

  file_upload_service:
    build:
      context: ./file_upload_service
      dockerfile: Dockerfile
    container_name: file_upload_service
    volumes:
      - static_data:/static_data
    networks:
      - transcendence

  auth_service_db_init:
    build:
      context: ./auth_service_db_init
      dockerfile: Dockerfile
    container_name: auth_service_db_init
    volumes:
      - sqlite_db_data:/sqlite_db_data
    networks:
      - transcendence

  game_service:
    build:
      context: ./game_service
      dockerfile: Dockerfile
    container_name: game_service
    networks:
      - transcendence

  match_service:
    build:
      context: ./match_service
      dockerfile: Dockerfile
    container_name: match_service
    networks:
      - transcendence

  rabbitmq_service:
    build:
      context: ./rabbitmq_service
      dockerfile: Dockerfile
    container_name: rabbitmq_service
    hostname: rabbitmq #are you using this for DNS?
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management console port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - transcendence

  proxy_service:
    build:
      context: ./proxy_service
      dockerfile: Dockerfile
    container_name: proxy_service
    volumes:
      - frontend_data:/frontend_data
      - static_data:/static_data
    ports:
      - "80:80"
    networks:
      - transcendence

  frontend_service:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: frontend_builder
    volumes:
      - /app/node_modules # anonymous volume -protect node_modules
      - frontend_data:/frontend_data # named volume for sharing frontend data with proxy_service
    command: >
      bash -c "npm run docker-build && npm run docker-build-css && cp -r /app/* /frontend_data/ && tail -f /dev/null"
    # build ts, css, copies data to named volume and keeps the container running!!!

networks:
  transcendence:
    driver: bridge


volumes:
  # sqlite
  sqlite_db_data:
  # file uploads for file_upload and proxy_service
  static_data:
  # index data
  frontend_data: