services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
#    depends_on:
#      - auth_service_db_init
    ports:
      - 80:3000
    volumes:
      - sqlite_db_data:/sqlite_db_data
    networks:
      - transcendence



networks:
  transcendence:
    driver: bridge


volumes:
  # sqlite
  sqlite_db_data: